import {StyleSheet} from 'react-native';

export const alertaStyles = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: '#f5f5f3' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  centeredText: { fontSize: 16, color: '#888', textAlign: 'center', marginBottom: 16 },
  botonPerfil: { backgroundColor: '#fff', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#C0221A' },
  header: { backgroundColor: '#C0221A', padding: 24, paddingTop: 48, paddingBottom: 20 },
  titulo: { color: '#fff', fontSize: 24, fontWeight: 'bold' },
  subtitulo: { color: 'rgba(255,255,255,0.8)', fontSize: 14, marginTop: 4 },
  scrollContainer: { padding: 16 },
  sinAlertas: { textAlign: 'center', marginTop: 40, color: '#888' },
  card: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 0.5, borderColor: '#e8e6df' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  badge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 20 },
  badgeText: { fontSize: 11, fontWeight: 'bold' },
  distancia: { fontSize: 12, color: '#888' },
  hospital: { fontSize: 16, fontWeight: 'bold', color: '#2c2c2a', marginBottom: 4 },
  direccion: { fontSize: 12, color: '#888', marginBottom: 8 },
  compatibleBadge: { backgroundColor: '#EAF3DE', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, alignSelf: 'flex-start', marginBottom: 12 },
  compatibleText: { fontSize: 11, color: '#3B6D11' },
  botones: { flexDirection: 'row', gap: 12, marginTop: 8 },
  btnAceptar: { flex: 1, backgroundColor: '#C0221A', paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  btnAceptarText: { color: '#fff', fontWeight: 'bold' },
  btnRechazar: { flex: 1, borderWidth: 1, borderColor: '#C0221A', paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  btnRechazarText: { color: '#C0221A', fontWeight: 'bold' },
});