import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f3" },

  // Header
  header: {
    backgroundColor: "#C0221A",
    padding: 20,
    paddingBottom: 28,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  greeting: { color: "rgba(255,255,255,0.8)", fontSize: 13 },
  nombre: { color: "white", fontSize: 20, fontWeight: "600", marginTop: 2 },
  tipoCard: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 10,
    padding: 10,
    alignItems: "center",
    minWidth: 64,
  },
  tipoSangre: { color: "white", fontSize: 22, fontWeight: "700" },
  tipoLabel: { color: "rgba(255,255,255,0.8)", fontSize: 10, marginTop: 2 },

  // Aptitud
  aptitudCard: {
    backgroundColor: "#EAF3DE",
    margin: 16,
    marginTop: -12,
    borderRadius: 10,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  aptitudDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#3B6D11" },
  aptitudText: { color: "#3B6D11", fontSize: 13, fontWeight: "500", flex: 1 },
  aptitudBtn: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, backgroundColor: "#3B6D11" },
  aptitudBtnTexto: { color: "white", fontSize: 11, fontWeight: "600" },

  // Alerta
  alertaBanner: {
    backgroundColor: "#FCEBEB",
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 14,
    borderWidth: 0.5,
    borderColor: "#F09595",
    marginBottom: 12,
  },
  alertaHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 6 },
  pulseDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#C0221A" },
  alertaTitulo: { color: "#A32D2D", fontWeight: "600", fontSize: 13, flex: 1 },
  alertaUrgencia: {
    backgroundColor: "#C0221A",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  alertaUrgenciaTexto: { color: "white", fontSize: 10, fontWeight: "600" },
  alertaBody: { color: "#C0221A", fontSize: 12, marginBottom: 10, lineHeight: 18 },
  alertaBotones: { flexDirection: "row", gap: 8 },
  btnAceptar: {
    backgroundColor: "#C0221A",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
  },
  btnAceptarText: { color: "white", fontSize: 12, fontWeight: "600" },
  btnRechazar: {
    borderWidth: 0.5,
    borderColor: "#F09595",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
  },
  btnRechazarText: { color: "#A32D2D", fontSize: 12 },

  // Secciones
  seccionTitulo: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2c2c2a",
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 10,
  },

  // Stats
  statsRow: { flexDirection: "row", marginHorizontal: 16, gap: 8 },
  statBox: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#e8e6df",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  statNum: { fontSize: 22, fontWeight: "700", color: "#2c2c2a" },
  statLabel: { fontSize: 10, color: "#888780", marginTop: 4, textAlign: "center" },

  // Acciones rápidas
  accionesRow: { flexDirection: "row", marginHorizontal: 16, gap: 8 },
  accionBtn: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    gap: 6,
    borderWidth: 0.5,
    borderColor: "#e8e6df",
  },
  accionBtnActivo: {
    backgroundColor: "#FCEBEB",
    borderColor: "#F09595",
  },
  accionIcono: { fontSize: 22 },
  accionLabel: { fontSize: 11, color: "#888780", fontWeight: "500", textAlign: "center" },
  accionLabelActivo: { color: "#C0221A" },

  // Próxima donación
  proximaCard: {
    backgroundColor: "white",
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 14,
    borderWidth: 0.5,
    borderColor: "#e8e6df",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  proximaIcono: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FCEBEB",
    alignItems: "center",
    justifyContent: "center",
  },
  proximaIconoTexto: { fontSize: 20 },
  proximaTitulo: { fontSize: 13, fontWeight: "600", color: "#2c2c2a" },
  proximaFecha: { fontSize: 12, color: "#888780", marginTop: 2 },
  proximaBadge: {
    marginLeft: "auto",
    backgroundColor: "#EAF3DE",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  proximaBadgeTexto: { fontSize: 11, color: "#3B6D11", fontWeight: "500" },

  // Historial
  historialItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 12,
    padding: 12,
    borderWidth: 0.5,
    borderColor: "#e8e6df",
    gap: 10,
  },
  historialIcono: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FCEBEB",
    alignItems: "center",
    justifyContent: "center",
  },
  historialCruz: { color: "#C0221A", fontSize: 18, fontWeight: "700" },
  historialInfo: { flex: 1 },
  historialHospital: { fontSize: 12, fontWeight: "500", color: "#2c2c2a" },
  historialFecha: { fontSize: 11, color: "#888780", marginTop: 2 },
  historialPuntos: { fontSize: 12, fontWeight: "600", color: "#3B6D11" },

  // Banner completar perfil
  bannerPerfil: {
    backgroundColor: "#E6F1FB",
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 0.5,
    borderColor: "#B5D4F4",
    marginBottom: 8,
  },
  bannerPerfilIcono: { fontSize: 20 },
  bannerPerfilTexto: { flex: 1, fontSize: 12, color: "#185FA5", lineHeight: 18 },
  bannerPerfilBtn: {
    backgroundColor: "#185FA5",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  bannerPerfilBtnTexto: { color: "white", fontSize: 11, fontWeight: "600" },
});